language: python

dist: xenial

cache: pip

python:
    - "3.6"
    - "3.7"

env:
    - TEST_DATABASE_URLS="postgresql://localhost/test_database, mysql://localhost/test_database, sqlite:///test.db, postgresql+aioodbc://localhost/test_database_aioodbc"

services:
    - postgresql
    - mysql

before_install:
    - sudo apt-get update
    - sudo apt-get install unixodbc-dev odbc-postgresql

install:
    - pip install -U -r requirements.txt

before_script:
    - psql -c 'create database test_database;' -U postgres
    - psql -c 'create database test_database_aioodbc;' -U postgres
    - echo 'create database test_database;' | mysql
    - sudo cp blthree/databases/odbcinst.ini /etc/odbcinst.ini

script:
    - scripts/test

after_script:
    - codecov
