language: python

dist: xenial

cache: pip

python:
    - "3.6"
    - "3.7"

env:
    - TEST_DATABASE_URLS="mssql+aioodbc://sa:Password123@localhost/test_database?driver=ODBC+Driver+17+for+SQL+Server&paramstyle=qmark&max_size=40"

services:
    - postgresql
    - mysql
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get install unixodbc-dev odbc-postgresql

install:
    - pip install -U -r requirements.txt

before_script:
    - psql -c 'create database test_database;' -U postgres
    - psql -c 'create database test_database_aioodbc;' -U postgres
    - echo 'create database test_database;' | mysql
    - docker run --name mssql-server-linux-latest -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Password123" -e "MSSQL_PID=Express" -p 1433:1433 -m 3G -d mcr.microsoft.com/mssql/server:2017-latest
    - sudo docker exec mssql-server-linux-latest /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Password123' -Q "CREATE DATABASE test_database"
    - bash install_mssql_odbc_driver
    - cat /etc/odbcinst.ini

script:
    - scripts/test

after_script:
    - codecov
